#!/bin/bash
# Generates lib/config/build_info.dart with real build metadata.
# Run this before building/deploying to capture the current state.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OUTPUT_FILE="$SCRIPT_DIR/lib/config/build_info.dart"

# Gather metadata
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git -C "$SCRIPT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_MACHINE=$(hostname -s 2>/dev/null || echo "unknown")

# Ensure config directory exists
mkdir -p "$SCRIPT_DIR/lib/config"

# Write the Dart file
cat > "$OUTPUT_FILE" << EOF
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by generate_build_info.sh at $BUILD_TIMESTAMP

/// Build metadata captured at compile/deploy time.
class BuildInfo {
  BuildInfo._();

  /// UTC timestamp of when the build was created.
  static const String buildTimestamp = '$BUILD_TIMESTAMP';

  /// Short git commit hash at build time.
  static const String gitCommit = '$GIT_COMMIT';

  /// Git branch name at build time.
  static const String gitBranch = '$GIT_BRANCH';

  /// Machine hostname that produced the build.
  static const String buildEnvironment = '$BUILD_MACHINE';
}
EOF

echo "✅ Generated $OUTPUT_FILE"
echo "   Timestamp:   $BUILD_TIMESTAMP"
echo "   Commit:      $GIT_COMMIT"
echo "   Branch:      $GIT_BRANCH"
echo "   Machine:     $BUILD_MACHINE"
